services:
  dev:
    # docker compose run --rm dev
    image: ${REGISTRY}/cbz-maker:dev
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - "./app:/app"
      - "./data:/data"

  app:
    # docker compose run --rm app
    image: ${REGISTRY}/cbz-maker:latest
    volumes:
      - "./data:/data"
