FROM python:3.14-slim

# Set environment variables for non-interactive installations
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# Update package list and install necessary dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        imagemagick zip poppler-utils \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "main.py"]
